// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjjchxfctjhbczxkwaqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqamNoeGZjdGpoYmN6eGt3YXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDMwOTUsImV4cCI6MjA1ODgxOTA5NX0.AK7Bu5qx0I4K1J_jbghoudZrYc1xqrmeplImxZPCb5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);