// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqendxwqeinjsuqhebou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZW5keHdxZWluanN1cWhlYm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODk2MjYsImV4cCI6MjA2MzE2NTYyNn0.vIClXdk3lMPXJmaDmI7pFowV2x1dPd1ieRzwQM1jgC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);